name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          npm install react-router-dom@6.x
          
      - name: Build
        env:
          REACT_APP_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PUBLIC_URL: 'https://malam-shadab.github.io/projectx'
        run: |
          cd frontend
          echo "Workflow run ID: $GITHUB_RUN_ID"
          echo "Run start time: $(date)"
          if [ -z "$REACT_APP_OPENAI_API_KEY" ]; then
            echo "No API key present - check repository secrets"
            exit 1
          else
            echo "API key prefix (first 5 chars): ${REACT_APP_OPENAI_API_KEY:0:5}"
          fi
          CI=false npm run build
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Deploy React app to GitHub Pages"